### ISSUE TITLE
Add support for  context in signal connections (like connect in qt 5.2)

### ISSUE THREAD

**Issue by katreniak** [robertknight/qt-signal-tools#3]
I pushed my implementation to master branch here:
https://github.com/katreniak/qt-signal-tools

Are you interested in it?

PS. Thanks for nice code.

**Comment by robertknight** [comment]
Hi - I think this is a good idea. Can you open a pull request? You should see an option to do so when you're looking at https://github.com/robertknight/qt-signal-tools

**Comment by robertknight** [comment]
Please add a test as well in TestQtSignalTools

**Comment by katreniak** [comment]
Pull request: https://github.com/robertknight/qt-signal-tools/pull/4
